### PR TITLE
Switch to @adrianheine/test262-parser for hashbang support

### PR DESCRIPTION
**Pull request by adrianheine**
See https://github.com/smikes/test262-parser/pull/14.

### CODE REVIEW

**Comment by rwaldron** [comment]
@adrianheine is the issue with test262-parser that @smikes is not responsive? (that's what it seems like)

**Comment by adrianheine** [comment]
Yes, unfortunately. He doesn't seem to be very active on GitHub anymore.

**Comment by rwaldron** [comment]
Ok, thanks

**Comment by adrianheine** [comment]
Maybe there's an organization that could host that repo to avoid having another situation like this.

**Comment by jugglinmike** [comment]
I'm not convinced that the separation of concerns is beneficial. It might make more sense to absorb the parser into this project.

**Comment by smikes** [comment]
Hey folks, I’m overseas at the moment dealing with a death in the family. Happy to pass on any repo that I own.

**Comment by smikes** [comment]
I just merged 2/3 PRs (3rd is conflicted) and published version 2.0.8 to npm.

**Comment by adrianheine** [comment]
Hi @smikes, thanks for handling this and sorry to bother you! I don't see any need for further action currently.

**Pull request closed without merging**
